Review Analysis using   --- TFIDF

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [4]:
data1= pd.read_csv('/content/drive/MyDrive/Reviews.csv')

In [5]:
list=data1.columns 


In [7]:
data2 = data1[data1['Score']!=3]
data2['Score'].unique()

array([5, 1, 4, 2])

In [8]:
X = data2['Text']

In [16]:
y_dictionary ={1:0,2:0,5:1,4:1}
Y = data2['Score'].map(y_dictionary)


In [23]:
def txt_fit(X,Y,nlp_mdl,ml_mdl,Show_value=False):
  X_Cv = nlp_mdl.fit_transform(X)
  print('features:{}'.format(X_Cv.shape[1]))
  X_train,X_test, Y_train , Y_test = train_test_split(X_Cv,Y)
  m= ml_mdl.fit(X_train,Y_train)
  accuracy =m.score(X_test,Y_test)
  print(accuracy)

  if Show_value == True:
    w = cvc.get_feature_names()
    Coefficent = m.coef_.tolist()[0]
    Coeff_Data = pd.DataFrame({'Word':w ,'Coefficient':Coefficent})
    Coeff_Data = Coeff_Data.sort_values(['Coefficient','Word'],ascending=False )
    print("\n")
    print("Top 10 Negative words")
    print(Coeff_Data.tail(10))
  


In [20]:
cvc = CountVectorizer(stop_words='english')

txt_fit(X,Y,cvc,LogisticRegression(),True) 


features:114969


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


0.9358558887519589


Top 10 Positive words
                 Word  Coefficient
67898        mediocre    -3.002032
41118     embarrassed    -3.126026
88945          ripoff    -3.129534
24949       cancelled    -3.213390
113164          worst    -3.264870
106852   unacceptable    -3.266484
37560   disappointing    -3.278005
65064           lousy    -3.293161
34989       deceptive    -4.034674
107383    undrinkable    -4.477026


In [11]:
from sklearn.metrics import confusion_matrix,accuracy_score
def pred(X,Y,nlp_mdl,ml_mdl):
  X_Cv = nlp_mdl.fit_transform(X)
  X_train,X_test, Y_train , Y_test = train_test_split(X_Cv,Y)
  m= ml_mdl.fit(X_train,Y_train)
  predctns = m.predict(X_test)
  cmtrx = confusion_matrix(predctns,Y_test)

  print(cmtrx)
  accscore = accuracy_score(predctns,Y_test)

  print(accscore)

In [12]:
pred(X,Y,CountVectorizer(stop_words='english'),LogisticRegression())

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


[[ 14944   2750]
 [  5417 108343]]
0.9378718030641897


In [21]:
from sklearn.dummy import DummyClassifier


In [25]:
txt_fit(X,Y,cvc,DummyClassifier(),False)

features:114969
0.7367900558370228


/usr/local/lib/python3.7/dist-packages/sklearn/dummy.py:132: FutureWarning: The default value of strategy will change from stratified to prior in 0.24.
  "stratified to prior in 0.24.", FutureWarning)


In [26]:
from sklearn.feature_extraction.text import TfidfVectorizer


In [27]:
tfidfV = TfidfVectorizer(stop_words='english')

In [29]:
txt_fit(X,Y,tfidfV,LogisticRegression(), True)

features:114969


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


0.9354374914418732


Top 10 Negative words
                  Word  Coefficient
103640           threw    -6.853643
111251            weak    -7.011182
107553   unfortunately    -7.376974
55168         horrible    -7.725264
37556     disappointed    -8.446700
11000            awful    -8.695159
37563   disappointment    -8.763269
102845        terrible    -9.122061
37560    disappointing    -9.958204
113164           worst   -11.773592


In [30]:
pred(X,Y,cvc,LogisticRegression())

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


[[ 14845   2714]
 [  5747 108148]]
0.9356352792611864


In [31]:
pred(X,Y,tfidfV,LogisticRegression())

[[ 14245   2353]
 [  6266 108590]]
0.9344333378976676


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
